"""Add foreign key table and column to discovered_columns

Revision ID: 75822ee87355
Revises: 7221618f8689
Create Date: 2025-10-04 13:16:12.032180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75822ee87355'
down_revision: Union[str, None] = '7221618f8689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovered_columns', sa.Column('foreign_key_table', sa.String(length=255), nullable=True))
    op.add_column('discovered_columns', sa.Column('foreign_key_column', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovered_columns', 'foreign_key_column')
    op.drop_column('discovered_columns', 'foreign_key_table')
    # ### end Alembic commands ###
